import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import ClerkProvider from "@/services/clerk/components/ClerkProvider";
import { ThemeProvider } from "next-themes";
import { Toaster } from "sonner";
import { Suspense } from "react";
import { Loader2Icon } from "lucide-react";

const outfitSans = Outfit({
  variable: "--font-outfit-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense
      fallback={
        <div className="h-screen w-full flex justify-center items-center">
          <Loader2Icon className="size-24 animate-spin" />
        </div>
      }
    >
      <ClerkProvider>
        <html lang="en" suppressHydrationWarning>
          <body
            className={`${outfitSans.variable} ${outfitSans.className} antialiased`}
          >
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableColorScheme
              disableTransitionOnChange
            >
              {children}
              <Toaster />
            </ThemeProvider>
          </body>
        </html>
      </ClerkProvider>
    </Suspense>
  );
}
